// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fare_service.proto

package fare_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateFareResponse struct {
	Fare                 *Fare    `protobuf:"bytes,1,opt,name=fare,proto3" json:"fare,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFareResponse) Reset()         { *m = CreateFareResponse{} }
func (m *CreateFareResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFareResponse) ProtoMessage()    {}
func (*CreateFareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_581d3f182827d35a, []int{0}
}

func (m *CreateFareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFareResponse.Unmarshal(m, b)
}
func (m *CreateFareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFareResponse.Marshal(b, m, deterministic)
}
func (m *CreateFareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFareResponse.Merge(m, src)
}
func (m *CreateFareResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFareResponse.Size(m)
}
func (m *CreateFareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFareResponse proto.InternalMessageInfo

func (m *CreateFareResponse) GetFare() *Fare {
	if m != nil {
		return m.Fare
	}
	return nil
}

type UpdateFareResponse struct {
	Fare                 *Fare    `protobuf:"bytes,1,opt,name=fare,proto3" json:"fare,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFareResponse) Reset()         { *m = UpdateFareResponse{} }
func (m *UpdateFareResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFareResponse) ProtoMessage()    {}
func (*UpdateFareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_581d3f182827d35a, []int{1}
}

func (m *UpdateFareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFareResponse.Unmarshal(m, b)
}
func (m *UpdateFareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFareResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFareResponse.Merge(m, src)
}
func (m *UpdateFareResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFareResponse.Size(m)
}
func (m *UpdateFareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFareResponse proto.InternalMessageInfo

func (m *UpdateFareResponse) GetFare() *Fare {
	if m != nil {
		return m.Fare
	}
	return nil
}

type GetFareRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFareRequest) Reset()         { *m = GetFareRequest{} }
func (m *GetFareRequest) String() string { return proto.CompactTextString(m) }
func (*GetFareRequest) ProtoMessage()    {}
func (*GetFareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_581d3f182827d35a, []int{2}
}

func (m *GetFareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFareRequest.Unmarshal(m, b)
}
func (m *GetFareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFareRequest.Marshal(b, m, deterministic)
}
func (m *GetFareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFareRequest.Merge(m, src)
}
func (m *GetFareRequest) XXX_Size() int {
	return xxx_messageInfo_GetFareRequest.Size(m)
}
func (m *GetFareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFareRequest proto.InternalMessageInfo

func (m *GetFareRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFareResponse struct {
	Fare                 *Fare    `protobuf:"bytes,1,opt,name=fare,proto3" json:"fare,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFareResponse) Reset()         { *m = GetFareResponse{} }
func (m *GetFareResponse) String() string { return proto.CompactTextString(m) }
func (*GetFareResponse) ProtoMessage()    {}
func (*GetFareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_581d3f182827d35a, []int{3}
}

func (m *GetFareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFareResponse.Unmarshal(m, b)
}
func (m *GetFareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFareResponse.Marshal(b, m, deterministic)
}
func (m *GetFareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFareResponse.Merge(m, src)
}
func (m *GetFareResponse) XXX_Size() int {
	return xxx_messageInfo_GetFareResponse.Size(m)
}
func (m *GetFareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFareResponse proto.InternalMessageInfo

func (m *GetFareResponse) GetFare() *Fare {
	if m != nil {
		return m.Fare
	}
	return nil
}

type GetAllFaresRequest struct {
	Limit                uint64   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 uint64   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllFaresRequest) Reset()         { *m = GetAllFaresRequest{} }
func (m *GetAllFaresRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllFaresRequest) ProtoMessage()    {}
func (*GetAllFaresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_581d3f182827d35a, []int{4}
}

func (m *GetAllFaresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllFaresRequest.Unmarshal(m, b)
}
func (m *GetAllFaresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllFaresRequest.Marshal(b, m, deterministic)
}
func (m *GetAllFaresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllFaresRequest.Merge(m, src)
}
func (m *GetAllFaresRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllFaresRequest.Size(m)
}
func (m *GetAllFaresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllFaresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllFaresRequest proto.InternalMessageInfo

func (m *GetAllFaresRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAllFaresRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetAllFaresResponse struct {
	Fares                []*Fare  `protobuf:"bytes,1,rep,name=fares,proto3" json:"fares,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllFaresResponse) Reset()         { *m = GetAllFaresResponse{} }
func (m *GetAllFaresResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllFaresResponse) ProtoMessage()    {}
func (*GetAllFaresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_581d3f182827d35a, []int{5}
}

func (m *GetAllFaresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllFaresResponse.Unmarshal(m, b)
}
func (m *GetAllFaresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllFaresResponse.Marshal(b, m, deterministic)
}
func (m *GetAllFaresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllFaresResponse.Merge(m, src)
}
func (m *GetAllFaresResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllFaresResponse.Size(m)
}
func (m *GetAllFaresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllFaresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllFaresResponse proto.InternalMessageInfo

func (m *GetAllFaresResponse) GetFares() []*Fare {
	if m != nil {
		return m.Fares
	}
	return nil
}

func (m *GetAllFaresResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DeleteFareRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFareRequest) Reset()         { *m = DeleteFareRequest{} }
func (m *DeleteFareRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFareRequest) ProtoMessage()    {}
func (*DeleteFareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_581d3f182827d35a, []int{6}
}

func (m *DeleteFareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFareRequest.Unmarshal(m, b)
}
func (m *DeleteFareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFareRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFareRequest.Merge(m, src)
}
func (m *DeleteFareRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFareRequest.Size(m)
}
func (m *DeleteFareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFareRequest proto.InternalMessageInfo

func (m *DeleteFareRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateFareResponse)(nil), "genproto.CreateFareResponse")
	proto.RegisterType((*UpdateFareResponse)(nil), "genproto.UpdateFareResponse")
	proto.RegisterType((*GetFareRequest)(nil), "genproto.GetFareRequest")
	proto.RegisterType((*GetFareResponse)(nil), "genproto.GetFareResponse")
	proto.RegisterType((*GetAllFaresRequest)(nil), "genproto.GetAllFaresRequest")
	proto.RegisterType((*GetAllFaresResponse)(nil), "genproto.GetAllFaresResponse")
	proto.RegisterType((*DeleteFareRequest)(nil), "genproto.DeleteFareRequest")
}

func init() {
	proto.RegisterFile("fare_service.proto", fileDescriptor_581d3f182827d35a)
}

var fileDescriptor_581d3f182827d35a = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0xa5, 0x20, 0x0e, 0x09, 0xc6, 0xf1, 0xab, 0x16, 0x4c, 0x9a, 0xd5, 0x03, 0xa7, 0x92,
	0x60, 0x4c, 0x38, 0xf9, 0x2d, 0x5c, 0xbc, 0x88, 0xf1, 0xe2, 0xc5, 0x14, 0x18, 0x9a, 0x26, 0x85,
	0xd6, 0xee, 0x62, 0xe2, 0xaf, 0xf4, 0x2f, 0x99, 0xdd, 0xa5, 0x7c, 0x6b, 0xa2, 0xb7, 0x9d, 0x79,
	0xf3, 0xde, 0xa4, 0xef, 0x4d, 0x01, 0x87, 0x7e, 0x4a, 0x6f, 0x9c, 0xd2, 0x8f, 0xb0, 0x4f, 0x5e,
	0x92, 0xc6, 0x22, 0xc6, 0x52, 0x40, 0x63, 0xf5, 0x72, 0x40, 0xa2, 0xba, 0xeb, 0x54, 0x83, 0x38,
	0x0e, 0x22, 0x6a, 0xa8, 0xaa, 0x37, 0x19, 0x36, 0x68, 0x94, 0x88, 0x4f, 0x0d, 0xb2, 0x16, 0xe0,
	0x5d, 0x4a, 0xbe, 0xa0, 0xb6, 0x9f, 0x52, 0x97, 0x78, 0x12, 0x8f, 0x39, 0x21, 0x03, 0x4b, 0x0a,
	0xd8, 0x86, 0x6b, 0xd4, 0xcb, 0xcd, 0x8a, 0x97, 0xe9, 0x7a, 0x6a, 0x4a, 0x61, 0x92, 0xf9, 0x92,
	0x0c, 0xfe, 0xc3, 0x74, 0xa1, 0xd2, 0x21, 0xa1, 0x69, 0xef, 0x13, 0xe2, 0x02, 0x2b, 0x60, 0x86,
	0x03, 0xc5, 0xd9, 0xee, 0x9a, 0xe1, 0x80, 0x5d, 0xc0, 0xce, 0x6c, 0xe2, 0x0f, 0xc2, 0x97, 0x80,
	0x1d, 0x12, 0x37, 0x51, 0x24, 0x7b, 0x3c, 0x13, 0xdf, 0x87, 0x42, 0x14, 0x8e, 0x42, 0x61, 0xe7,
	0x5d, 0xa3, 0x6e, 0x75, 0x75, 0x81, 0x08, 0x56, 0xe2, 0x07, 0x64, 0x5b, 0xaa, 0xa9, 0xde, 0xec,
	0x09, 0xf6, 0x96, 0xf8, 0xd3, 0xd5, 0x67, 0x50, 0x90, 0xf2, 0xdc, 0x36, 0xdc, 0xfc, 0x86, 0xdd,
	0x1a, 0x94, 0x6b, 0xfa, 0xf1, 0x64, 0x2c, 0x6c, 0x53, 0xaf, 0x51, 0x05, 0x3b, 0x85, 0xdd, 0x7b,
	0x8a, 0x28, 0x73, 0x69, 0xe3, 0xe7, 0x36, 0xbf, 0x4c, 0x28, 0xb5, 0x9f, 0x75, 0x94, 0xd8, 0x82,
	0xa2, 0x4e, 0x04, 0x57, 0x16, 0x39, 0xb5, 0x79, 0xbd, 0x9e, 0x19, 0xcb, 0x49, 0xa6, 0x4e, 0xe4,
	0x37, 0xe6, 0x7a, 0x66, 0x2c, 0x87, 0xd7, 0xb0, 0x35, 0xf5, 0x1b, 0xed, 0xf9, 0xe8, 0x72, 0x48,
	0xce, 0xf1, 0x06, 0x64, 0xa6, 0xf0, 0x08, 0xe5, 0x05, 0xeb, 0xb0, 0xb6, 0x34, 0xbb, 0x92, 0x88,
	0x73, 0xf2, 0x03, 0x3a, 0x53, 0xbb, 0x82, 0xa2, 0x76, 0x0d, 0xab, 0xf3, 0xd1, 0x35, 0x1f, 0x9d,
	0x43, 0x4f, 0x9f, 0xb6, 0x97, 0x9d, 0xb6, 0xf7, 0x20, 0x4f, 0x9b, 0xe5, 0x6e, 0x8f, 0x5e, 0x0f,
	0x32, 0x5e, 0x63, 0xf1, 0x47, 0xe9, 0x15, 0x55, 0xef, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x36,
	0x4c, 0xa0, 0x42, 0x3f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FServiceClient is the client API for FService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FServiceClient interface {
	Create(ctx context.Context, in *Fare, opts ...grpc.CallOption) (*CreateFareResponse, error)
	Update(ctx context.Context, in *Fare, opts ...grpc.CallOption) (*UpdateFareResponse, error)
	GetFare(ctx context.Context, in *GetFareRequest, opts ...grpc.CallOption) (*GetFareResponse, error)
	GetAllFares(ctx context.Context, in *GetAllFaresRequest, opts ...grpc.CallOption) (*GetAllFaresResponse, error)
	Delete(ctx context.Context, in *DeleteFareRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type fServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFServiceClient(cc grpc.ClientConnInterface) FServiceClient {
	return &fServiceClient{cc}
}

func (c *fServiceClient) Create(ctx context.Context, in *Fare, opts ...grpc.CallOption) (*CreateFareResponse, error) {
	out := new(CreateFareResponse)
	err := c.cc.Invoke(ctx, "/genproto.FService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fServiceClient) Update(ctx context.Context, in *Fare, opts ...grpc.CallOption) (*UpdateFareResponse, error) {
	out := new(UpdateFareResponse)
	err := c.cc.Invoke(ctx, "/genproto.FService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fServiceClient) GetFare(ctx context.Context, in *GetFareRequest, opts ...grpc.CallOption) (*GetFareResponse, error) {
	out := new(GetFareResponse)
	err := c.cc.Invoke(ctx, "/genproto.FService/GetFare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fServiceClient) GetAllFares(ctx context.Context, in *GetAllFaresRequest, opts ...grpc.CallOption) (*GetAllFaresResponse, error) {
	out := new(GetAllFaresResponse)
	err := c.cc.Invoke(ctx, "/genproto.FService/GetAllFares", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fServiceClient) Delete(ctx context.Context, in *DeleteFareRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/genproto.FService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FServiceServer is the server API for FService service.
type FServiceServer interface {
	Create(context.Context, *Fare) (*CreateFareResponse, error)
	Update(context.Context, *Fare) (*UpdateFareResponse, error)
	GetFare(context.Context, *GetFareRequest) (*GetFareResponse, error)
	GetAllFares(context.Context, *GetAllFaresRequest) (*GetAllFaresResponse, error)
	Delete(context.Context, *DeleteFareRequest) (*empty.Empty, error)
}

// UnimplementedFServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFServiceServer struct {
}

func (*UnimplementedFServiceServer) Create(ctx context.Context, req *Fare) (*CreateFareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedFServiceServer) Update(ctx context.Context, req *Fare) (*UpdateFareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedFServiceServer) GetFare(ctx context.Context, req *GetFareRequest) (*GetFareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFare not implemented")
}
func (*UnimplementedFServiceServer) GetAllFares(ctx context.Context, req *GetAllFaresRequest) (*GetAllFaresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFares not implemented")
}
func (*UnimplementedFServiceServer) Delete(ctx context.Context, req *DeleteFareRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterFServiceServer(s *grpc.Server, srv FServiceServer) {
	s.RegisterService(&_FService_serviceDesc, srv)
}

func _FService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Fare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.FService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FServiceServer).Create(ctx, req.(*Fare))
	}
	return interceptor(ctx, in, info, handler)
}

func _FService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Fare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.FService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FServiceServer).Update(ctx, req.(*Fare))
	}
	return interceptor(ctx, in, info, handler)
}

func _FService_GetFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FServiceServer).GetFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.FService/GetFare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FServiceServer).GetFare(ctx, req.(*GetFareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FService_GetAllFares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFaresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FServiceServer).GetAllFares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.FService/GetAllFares",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FServiceServer).GetAllFares(ctx, req.(*GetAllFaresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.FService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FServiceServer).Delete(ctx, req.(*DeleteFareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.FService",
	HandlerType: (*FServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _FService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _FService_Update_Handler,
		},
		{
			MethodName: "GetFare",
			Handler:    _FService_GetFare_Handler,
		},
		{
			MethodName: "GetAllFares",
			Handler:    _FService_GetAllFares_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _FService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fare_service.proto",
}
