// Code generated by protoc-gen-go. DO NOT EDIT.
// source: courier.proto

package courier_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Courier struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DistributorId        string   `protobuf:"bytes,2,opt,name=distributor_id,json=distributorId,proto3" json:"distributor_id,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status               bool     `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	AccessToken          string   `protobuf:"bytes,8,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Courier) Reset()         { *m = Courier{} }
func (m *Courier) String() string { return proto.CompactTextString(m) }
func (*Courier) ProtoMessage()    {}
func (*Courier) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a821f38f6bc4e38, []int{0}
}

func (m *Courier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Courier.Unmarshal(m, b)
}
func (m *Courier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Courier.Marshal(b, m, deterministic)
}
func (m *Courier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Courier.Merge(m, src)
}
func (m *Courier) XXX_Size() int {
	return xxx_messageInfo_Courier.Size(m)
}
func (m *Courier) XXX_DiscardUnknown() {
	xxx_messageInfo_Courier.DiscardUnknown(m)
}

var xxx_messageInfo_Courier proto.InternalMessageInfo

func (m *Courier) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Courier) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *Courier) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Courier) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Courier) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Courier) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Courier) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Courier) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type CourierDetails struct {
	CourierId            string                `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	PassportNumber       string                `protobuf:"bytes,2,opt,name=passport_number,json=passportNumber,proto3" json:"passport_number,omitempty"`
	Gender               *wrappers.StringValue `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate            string                `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Address              *wrappers.StringValue `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Img                  *wrappers.StringValue `protobuf:"bytes,6,opt,name=img,proto3" json:"img,omitempty"`
	LisenseNumber        string                `protobuf:"bytes,7,opt,name=lisense_number,json=lisenseNumber,proto3" json:"lisense_number,omitempty"`
	LisenseGivenDate     string                `protobuf:"bytes,8,opt,name=lisense_given_date,json=lisenseGivenDate,proto3" json:"lisense_given_date,omitempty"`
	LisenseExpiryDate    string                `protobuf:"bytes,9,opt,name=lisense_expiry_date,json=lisenseExpiryDate,proto3" json:"lisense_expiry_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CourierDetails) Reset()         { *m = CourierDetails{} }
func (m *CourierDetails) String() string { return proto.CompactTextString(m) }
func (*CourierDetails) ProtoMessage()    {}
func (*CourierDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a821f38f6bc4e38, []int{1}
}

func (m *CourierDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourierDetails.Unmarshal(m, b)
}
func (m *CourierDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourierDetails.Marshal(b, m, deterministic)
}
func (m *CourierDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourierDetails.Merge(m, src)
}
func (m *CourierDetails) XXX_Size() int {
	return xxx_messageInfo_CourierDetails.Size(m)
}
func (m *CourierDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CourierDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CourierDetails proto.InternalMessageInfo

func (m *CourierDetails) GetCourierId() string {
	if m != nil {
		return m.CourierId
	}
	return ""
}

func (m *CourierDetails) GetPassportNumber() string {
	if m != nil {
		return m.PassportNumber
	}
	return ""
}

func (m *CourierDetails) GetGender() *wrappers.StringValue {
	if m != nil {
		return m.Gender
	}
	return nil
}

func (m *CourierDetails) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *CourierDetails) GetAddress() *wrappers.StringValue {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *CourierDetails) GetImg() *wrappers.StringValue {
	if m != nil {
		return m.Img
	}
	return nil
}

func (m *CourierDetails) GetLisenseNumber() string {
	if m != nil {
		return m.LisenseNumber
	}
	return ""
}

func (m *CourierDetails) GetLisenseGivenDate() string {
	if m != nil {
		return m.LisenseGivenDate
	}
	return ""
}

func (m *CourierDetails) GetLisenseExpiryDate() string {
	if m != nil {
		return m.LisenseExpiryDate
	}
	return ""
}

type CourierVehicle struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourierId            string   `protobuf:"bytes,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	VehicleNumber        string   `protobuf:"bytes,4,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status               bool     `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourierVehicle) Reset()         { *m = CourierVehicle{} }
func (m *CourierVehicle) String() string { return proto.CompactTextString(m) }
func (*CourierVehicle) ProtoMessage()    {}
func (*CourierVehicle) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a821f38f6bc4e38, []int{2}
}

func (m *CourierVehicle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourierVehicle.Unmarshal(m, b)
}
func (m *CourierVehicle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourierVehicle.Marshal(b, m, deterministic)
}
func (m *CourierVehicle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourierVehicle.Merge(m, src)
}
func (m *CourierVehicle) XXX_Size() int {
	return xxx_messageInfo_CourierVehicle.Size(m)
}
func (m *CourierVehicle) XXX_DiscardUnknown() {
	xxx_messageInfo_CourierVehicle.DiscardUnknown(m)
}

var xxx_messageInfo_CourierVehicle proto.InternalMessageInfo

func (m *CourierVehicle) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourierVehicle) GetCourierId() string {
	if m != nil {
		return m.CourierId
	}
	return ""
}

func (m *CourierVehicle) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *CourierVehicle) GetVehicleNumber() string {
	if m != nil {
		return m.VehicleNumber
	}
	return ""
}

func (m *CourierVehicle) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *CourierVehicle) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Courier)(nil), "genproto.Courier")
	proto.RegisterType((*CourierDetails)(nil), "genproto.CourierDetails")
	proto.RegisterType((*CourierVehicle)(nil), "genproto.CourierVehicle")
}

func init() { proto.RegisterFile("courier.proto", fileDescriptor_3a821f38f6bc4e38) }

var fileDescriptor_3a821f38f6bc4e38 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0x5a, 0x9a, 0x36, 0x77, 0xb4, 0x80, 0x99, 0x50, 0x34, 0x18, 0x1a, 0x95, 0x10, 0x7b,
	0x40, 0xa9, 0x04, 0x88, 0x77, 0x60, 0x08, 0xed, 0x65, 0x0f, 0x05, 0xed, 0x81, 0x97, 0xc8, 0x89,
	0xef, 0x52, 0x8b, 0x24, 0x8e, 0x6c, 0xa7, 0xc0, 0xaf, 0xf0, 0x1b, 0xfc, 0x16, 0x1f, 0x81, 0x72,
	0x6d, 0x57, 0x1b, 0x68, 0xea, 0x5b, 0xee, 0x39, 0xe7, 0xda, 0x3e, 0xe7, 0xde, 0xc0, 0xbc, 0x54,
	0xbd, 0x96, 0xa8, 0xb3, 0x4e, 0x2b, 0xab, 0xd8, 0xac, 0xc2, 0x96, 0xbe, 0x8e, 0x9e, 0x56, 0x4a,
	0x55, 0x35, 0xae, 0xa8, 0x2a, 0xfa, 0xab, 0xd5, 0x77, 0xcd, 0xbb, 0x0e, 0xb5, 0x71, 0xca, 0xe5,
	0x9f, 0x08, 0xa6, 0x1f, 0x5c, 0x2f, 0x5b, 0xc0, 0x48, 0x8a, 0x34, 0x3a, 0x89, 0x4e, 0x93, 0xf5,
	0x48, 0x0a, 0xf6, 0x1c, 0x16, 0x42, 0x1a, 0xab, 0x65, 0xd1, 0x5b, 0xa5, 0x73, 0x29, 0xd2, 0x11,
	0x71, 0xf3, 0x6b, 0xe8, 0xb9, 0x60, 0x87, 0x30, 0xe9, 0x36, 0xaa, 0xc5, 0x74, 0x4c, 0xac, 0x2b,
	0xd8, 0x31, 0xc0, 0x95, 0xd4, 0xc6, 0xe6, 0x2d, 0x6f, 0x30, 0xbd, 0x43, 0x54, 0x42, 0xc8, 0x05,
	0x6f, 0x90, 0x3d, 0x86, 0xa4, 0xe6, 0x81, 0x9d, 0x10, 0x3b, 0x1b, 0x00, 0x22, 0x8f, 0x01, 0x4a,
	0x8d, 0xdc, 0xa2, 0xc8, 0xb9, 0x4d, 0x63, 0xd7, 0xeb, 0x91, 0x77, 0x96, 0x3d, 0x82, 0xd8, 0x58,
	0x6e, 0x7b, 0x93, 0x4e, 0x4f, 0xa2, 0xd3, 0xd9, 0xda, 0x57, 0xec, 0x19, 0xdc, 0xe5, 0x65, 0x89,
	0xc6, 0xe4, 0x56, 0x7d, 0xc3, 0x36, 0x9d, 0x51, 0xe3, 0x81, 0xc3, 0xbe, 0x0c, 0xd0, 0xf2, 0xd7,
	0x18, 0x16, 0xde, 0xee, 0x19, 0x5a, 0x2e, 0x6b, 0x43, 0x97, 0x39, 0x24, 0xdf, 0xb9, 0x4f, 0x3c,
	0x72, 0x2e, 0xd8, 0x0b, 0xb8, 0xd7, 0x71, 0x63, 0x3a, 0xa5, 0x6d, 0xde, 0xf6, 0x4d, 0x81, 0xda,
	0xa7, 0xb0, 0x08, 0xf0, 0x05, 0xa1, 0xec, 0x0d, 0xc4, 0x15, 0xb6, 0x02, 0x35, 0xe5, 0x70, 0xf0,
	0xea, 0x49, 0xe6, 0xa2, 0xcf, 0x42, 0xf4, 0xd9, 0x67, 0xab, 0x65, 0x5b, 0x5d, 0xf2, 0xba, 0xc7,
	0xb5, 0xd7, 0x0e, 0xb7, 0x17, 0x52, 0xdb, 0x4d, 0x2e, 0xb8, 0xdd, 0xc5, 0x44, 0xc8, 0x19, 0xb7,
	0xc8, 0xde, 0xc2, 0x94, 0x0b, 0xa1, 0xd1, 0x18, 0x0a, 0x69, 0xdf, 0xa9, 0x41, 0xcc, 0x32, 0x18,
	0xcb, 0xa6, 0xa2, 0xe8, 0xf6, 0xf5, 0x0c, 0xc2, 0x61, 0xd4, 0xb5, 0x34, 0xd8, 0x1a, 0x0c, 0x26,
	0xa7, 0x6e, 0xd4, 0x1e, 0xf5, 0x1e, 0x5f, 0x02, 0x0b, 0xb2, 0x4a, 0x6e, 0xb1, 0x75, 0xaf, 0x76,
	0x39, 0xdf, 0xf7, 0xcc, 0xa7, 0x81, 0xa0, 0xc7, 0x67, 0xf0, 0x30, 0xa8, 0xf1, 0x47, 0x27, 0xf5,
	0x4f, 0x27, 0x4f, 0x48, 0xfe, 0xc0, 0x53, 0x1f, 0x89, 0x19, 0xf4, 0xcb, 0xdf, 0xd1, 0x6e, 0x38,
	0x97, 0xb8, 0x91, 0x65, 0x8d, 0xff, 0xad, 0xe4, 0xcd, 0x61, 0x8d, 0xfe, 0x1d, 0xd6, 0x21, 0x4c,
	0x1a, 0x25, 0xb0, 0x0e, 0xab, 0x48, 0xc5, 0x60, 0x6e, 0xeb, 0xce, 0x0b, 0xe6, 0x5c, 0xce, 0x73,
	0x8f, 0x7a, 0x73, 0x37, 0xb7, 0x6e, 0x72, 0xfb, 0xd6, 0xc5, 0xd7, 0xb7, 0xee, 0xfd, 0xd1, 0xd7,
	0x34, 0xfc, 0x6d, 0xab, 0xf0, 0x36, 0x83, 0x7a, 0x2b, 0x4b, 0x2c, 0x62, 0x82, 0x5f, 0xff, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xa2, 0xf6, 0xc8, 0x00, 0x9f, 0x03, 0x00, 0x00,
}
