// Code generated by protoc-gen-go. DO NOT EDIT.
// source: courier_service.proto

package courier_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCourierResponse struct {
	Courier              *Courier `protobuf:"bytes,1,opt,name=courier,proto3" json:"courier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCourierResponse) Reset()         { *m = CreateCourierResponse{} }
func (m *CreateCourierResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCourierResponse) ProtoMessage()    {}
func (*CreateCourierResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_902b1fc4851aa94a, []int{0}
}

func (m *CreateCourierResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCourierResponse.Unmarshal(m, b)
}
func (m *CreateCourierResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCourierResponse.Marshal(b, m, deterministic)
}
func (m *CreateCourierResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCourierResponse.Merge(m, src)
}
func (m *CreateCourierResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCourierResponse.Size(m)
}
func (m *CreateCourierResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCourierResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCourierResponse proto.InternalMessageInfo

func (m *CreateCourierResponse) GetCourier() *Courier {
	if m != nil {
		return m.Courier
	}
	return nil
}

type UpdateCourierResponse struct {
	Courier              *Courier `protobuf:"bytes,1,opt,name=courier,proto3" json:"courier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCourierResponse) Reset()         { *m = UpdateCourierResponse{} }
func (m *UpdateCourierResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCourierResponse) ProtoMessage()    {}
func (*UpdateCourierResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_902b1fc4851aa94a, []int{1}
}

func (m *UpdateCourierResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCourierResponse.Unmarshal(m, b)
}
func (m *UpdateCourierResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCourierResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCourierResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCourierResponse.Merge(m, src)
}
func (m *UpdateCourierResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCourierResponse.Size(m)
}
func (m *UpdateCourierResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCourierResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCourierResponse proto.InternalMessageInfo

func (m *UpdateCourierResponse) GetCourier() *Courier {
	if m != nil {
		return m.Courier
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateCourierResponse)(nil), "genproto.CreateCourierResponse")
	proto.RegisterType((*UpdateCourierResponse)(nil), "genproto.UpdateCourierResponse")
}

func init() { proto.RegisterFile("courier_service.proto", fileDescriptor_902b1fc4851aa94a) }

var fileDescriptor_902b1fc4851aa94a = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xce, 0x2f, 0x2d,
	0xca, 0x4c, 0x2d, 0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x48, 0x4f, 0xcd, 0x03, 0xb3, 0xa4, 0x78, 0xa1, 0x0a, 0x20, 0x12, 0x4a, 0x2e,
	0x5c, 0xa2, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0xce, 0x10, 0xe1, 0xa0, 0xd4, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x21, 0x6d, 0x2e, 0x76, 0xa8, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23,
	0x41, 0x3d, 0x98, 0x19, 0x7a, 0x30, 0xb5, 0x30, 0x15, 0x20, 0x53, 0x42, 0x0b, 0x52, 0x28, 0x34,
	0xc5, 0x68, 0x02, 0x23, 0x17, 0x1f, 0x54, 0x30, 0x18, 0xe2, 0x7a, 0x21, 0x3b, 0x2e, 0x36, 0x88,
	0xf3, 0x84, 0x30, 0x35, 0x4a, 0xc9, 0x23, 0x09, 0x61, 0xf3, 0x83, 0x12, 0x03, 0x48, 0x3f, 0xc4,
	0x61, 0x04, 0xf4, 0x63, 0x75, 0xbd, 0x12, 0x83, 0x93, 0x54, 0x94, 0x04, 0x4c, 0x8d, 0x3e, 0x5a,
	0xc8, 0x26, 0xb1, 0x81, 0x85, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xd6, 0xe1, 0xc7,
	0x73, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CourierServiceClient is the client API for CourierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CourierServiceClient interface {
	Create(ctx context.Context, in *Courier, opts ...grpc.CallOption) (*CreateCourierResponse, error)
	Update(ctx context.Context, in *Courier, opts ...grpc.CallOption) (*UpdateCourierResponse, error)
}

type courierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCourierServiceClient(cc grpc.ClientConnInterface) CourierServiceClient {
	return &courierServiceClient{cc}
}

func (c *courierServiceClient) Create(ctx context.Context, in *Courier, opts ...grpc.CallOption) (*CreateCourierResponse, error) {
	out := new(CreateCourierResponse)
	err := c.cc.Invoke(ctx, "/genproto.CourierService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierServiceClient) Update(ctx context.Context, in *Courier, opts ...grpc.CallOption) (*UpdateCourierResponse, error) {
	out := new(UpdateCourierResponse)
	err := c.cc.Invoke(ctx, "/genproto.CourierService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourierServiceServer is the server API for CourierService service.
type CourierServiceServer interface {
	Create(context.Context, *Courier) (*CreateCourierResponse, error)
	Update(context.Context, *Courier) (*UpdateCourierResponse, error)
}

// UnimplementedCourierServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCourierServiceServer struct {
}

func (*UnimplementedCourierServiceServer) Create(ctx context.Context, req *Courier) (*CreateCourierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCourierServiceServer) Update(ctx context.Context, req *Courier) (*UpdateCourierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterCourierServiceServer(s *grpc.Server, srv CourierServiceServer) {
	s.RegisterService(&_CourierService_serviceDesc, srv)
}

func _CourierService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Courier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.CourierService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServiceServer).Create(ctx, req.(*Courier))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Courier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.CourierService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServiceServer).Update(ctx, req.(*Courier))
	}
	return interceptor(ctx, in, info, handler)
}

var _CourierService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.CourierService",
	HandlerType: (*CourierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CourierService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CourierService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "courier_service.proto",
}
