// Code generated by protoc-gen-go. DO NOT EDIT.
// source: courier.proto

package courier_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Courier struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreateAt             string   `protobuf:"bytes,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	Status               bool     `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Courier) Reset()         { *m = Courier{} }
func (m *Courier) String() string { return proto.CompactTextString(m) }
func (*Courier) ProtoMessage()    {}
func (*Courier) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a821f38f6bc4e38, []int{0}
}

func (m *Courier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Courier.Unmarshal(m, b)
}
func (m *Courier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Courier.Marshal(b, m, deterministic)
}
func (m *Courier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Courier.Merge(m, src)
}
func (m *Courier) XXX_Size() int {
	return xxx_messageInfo_Courier.Size(m)
}
func (m *Courier) XXX_DiscardUnknown() {
	xxx_messageInfo_Courier.DiscardUnknown(m)
}

var xxx_messageInfo_Courier proto.InternalMessageInfo

func (m *Courier) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Courier) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Courier) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Courier) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Courier) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *Courier) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type CourierDetails struct {
	CourierId            string   `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	PassportNumber       string   `protobuf:"bytes,2,opt,name=passport_number,json=passportNumber,proto3" json:"passport_number,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate            string   `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Img                  string   `protobuf:"bytes,6,opt,name=img,proto3" json:"img,omitempty"`
	LisenseNumber        string   `protobuf:"bytes,7,opt,name=lisense_number,json=lisenseNumber,proto3" json:"lisense_number,omitempty"`
	LisenseGivenDate     string   `protobuf:"bytes,8,opt,name=lisense_given_date,json=lisenseGivenDate,proto3" json:"lisense_given_date,omitempty"`
	LisenseExpiryDate    string   `protobuf:"bytes,9,opt,name=lisense_expiry_date,json=lisenseExpiryDate,proto3" json:"lisense_expiry_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourierDetails) Reset()         { *m = CourierDetails{} }
func (m *CourierDetails) String() string { return proto.CompactTextString(m) }
func (*CourierDetails) ProtoMessage()    {}
func (*CourierDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a821f38f6bc4e38, []int{1}
}

func (m *CourierDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourierDetails.Unmarshal(m, b)
}
func (m *CourierDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourierDetails.Marshal(b, m, deterministic)
}
func (m *CourierDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourierDetails.Merge(m, src)
}
func (m *CourierDetails) XXX_Size() int {
	return xxx_messageInfo_CourierDetails.Size(m)
}
func (m *CourierDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CourierDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CourierDetails proto.InternalMessageInfo

func (m *CourierDetails) GetCourierId() string {
	if m != nil {
		return m.CourierId
	}
	return ""
}

func (m *CourierDetails) GetPassportNumber() string {
	if m != nil {
		return m.PassportNumber
	}
	return ""
}

func (m *CourierDetails) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *CourierDetails) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *CourierDetails) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CourierDetails) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *CourierDetails) GetLisenseNumber() string {
	if m != nil {
		return m.LisenseNumber
	}
	return ""
}

func (m *CourierDetails) GetLisenseGivenDate() string {
	if m != nil {
		return m.LisenseGivenDate
	}
	return ""
}

func (m *CourierDetails) GetLisenseExpiryDate() string {
	if m != nil {
		return m.LisenseExpiryDate
	}
	return ""
}

type CourierFare struct {
	CourierId            string   `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	FareId               string   `protobuf:"bytes,2,opt,name=fare_id,json=fareId,proto3" json:"fare_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourierFare) Reset()         { *m = CourierFare{} }
func (m *CourierFare) String() string { return proto.CompactTextString(m) }
func (*CourierFare) ProtoMessage()    {}
func (*CourierFare) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a821f38f6bc4e38, []int{2}
}

func (m *CourierFare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourierFare.Unmarshal(m, b)
}
func (m *CourierFare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourierFare.Marshal(b, m, deterministic)
}
func (m *CourierFare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourierFare.Merge(m, src)
}
func (m *CourierFare) XXX_Size() int {
	return xxx_messageInfo_CourierFare.Size(m)
}
func (m *CourierFare) XXX_DiscardUnknown() {
	xxx_messageInfo_CourierFare.DiscardUnknown(m)
}

var xxx_messageInfo_CourierFare proto.InternalMessageInfo

func (m *CourierFare) GetCourierId() string {
	if m != nil {
		return m.CourierId
	}
	return ""
}

func (m *CourierFare) GetFareId() string {
	if m != nil {
		return m.FareId
	}
	return ""
}

type CourierVehicle struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourierId            string   `protobuf:"bytes,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	VehicleNumber        string   `protobuf:"bytes,4,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status               bool     `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourierVehicle) Reset()         { *m = CourierVehicle{} }
func (m *CourierVehicle) String() string { return proto.CompactTextString(m) }
func (*CourierVehicle) ProtoMessage()    {}
func (*CourierVehicle) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a821f38f6bc4e38, []int{3}
}

func (m *CourierVehicle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourierVehicle.Unmarshal(m, b)
}
func (m *CourierVehicle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourierVehicle.Marshal(b, m, deterministic)
}
func (m *CourierVehicle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourierVehicle.Merge(m, src)
}
func (m *CourierVehicle) XXX_Size() int {
	return xxx_messageInfo_CourierVehicle.Size(m)
}
func (m *CourierVehicle) XXX_DiscardUnknown() {
	xxx_messageInfo_CourierVehicle.DiscardUnknown(m)
}

var xxx_messageInfo_CourierVehicle proto.InternalMessageInfo

func (m *CourierVehicle) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourierVehicle) GetCourierId() string {
	if m != nil {
		return m.CourierId
	}
	return ""
}

func (m *CourierVehicle) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *CourierVehicle) GetVehicleNumber() string {
	if m != nil {
		return m.VehicleNumber
	}
	return ""
}

func (m *CourierVehicle) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *CourierVehicle) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Courier)(nil), "genproto.Courier")
	proto.RegisterType((*CourierDetails)(nil), "genproto.CourierDetails")
	proto.RegisterType((*CourierFare)(nil), "genproto.CourierFare")
	proto.RegisterType((*CourierVehicle)(nil), "genproto.CourierVehicle")
}

func init() { proto.RegisterFile("courier.proto", fileDescriptor_3a821f38f6bc4e38) }

var fileDescriptor_3a821f38f6bc4e38 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0xae, 0xd3, 0x30,
	0x10, 0x85, 0x95, 0x5c, 0x9a, 0x9f, 0x41, 0x0d, 0x17, 0x73, 0x05, 0x11, 0x08, 0xa9, 0x8a, 0x84,
	0xe8, 0x02, 0x95, 0x05, 0x4f, 0x00, 0xb4, 0xa0, 0x6e, 0xba, 0xe8, 0x82, 0x05, 0x9b, 0xc8, 0x8d,
	0xa7, 0xa9, 0xa5, 0xfc, 0xc9, 0x76, 0x2b, 0x78, 0x1b, 0xde, 0x81, 0x17, 0xe0, 0xd1, 0x90, 0xed,
	0x71, 0x11, 0x20, 0xc4, 0x2e, 0x73, 0xbe, 0xd1, 0xf8, 0xcc, 0xc9, 0xc0, 0xbc, 0x19, 0xcf, 0x4a,
	0xa2, 0x5a, 0x4d, 0x6a, 0x34, 0x23, 0xcb, 0x5a, 0x1c, 0xdc, 0x57, 0xf5, 0x2d, 0x82, 0xf4, 0xbd,
	0x67, 0xac, 0x80, 0x58, 0x8a, 0x32, 0x5a, 0x44, 0xcb, 0x7c, 0x1f, 0x4b, 0xc1, 0xee, 0x60, 0x36,
	0x9d, 0xc6, 0x01, 0xcb, 0xd8, 0x49, 0xbe, 0x60, 0xcf, 0x01, 0x8e, 0x52, 0x69, 0x53, 0x0f, 0xbc,
	0xc7, 0xf2, 0xc6, 0xa1, 0xdc, 0x29, 0x3b, 0xde, 0x23, 0x7b, 0x06, 0x79, 0xc7, 0x03, 0xbd, 0xe7,
	0x68, 0x66, 0x85, 0x00, 0x1b, 0x85, 0xdc, 0x60, 0xcd, 0x4d, 0x39, 0xf3, 0xd0, 0x0b, 0x6f, 0x0d,
	0x7b, 0x0c, 0x89, 0x36, 0xdc, 0x9c, 0x75, 0x99, 0x2c, 0xa2, 0x65, 0xb6, 0xa7, 0xaa, 0xfa, 0x11,
	0x43, 0x41, 0x16, 0xd7, 0x68, 0xb8, 0xec, 0xb4, 0xf5, 0x40, 0x0b, 0xd5, 0x57, 0xc7, 0x39, 0x29,
	0x5b, 0xc1, 0x5e, 0xc2, 0x83, 0x89, 0x6b, 0x3d, 0x8d, 0xca, 0xd4, 0xc3, 0xb9, 0x3f, 0xa0, 0xa2,
	0x15, 0x8a, 0x20, 0xef, 0x9c, 0x6a, 0x9f, 0x6c, 0x71, 0x10, 0xa8, 0x68, 0x0f, 0xaa, 0xec, 0xfc,
	0x83, 0x54, 0xe6, 0x54, 0x0b, 0x6e, 0xc2, 0x16, 0xb9, 0x53, 0xd6, 0xdc, 0x20, 0x2b, 0x21, 0xe5,
	0x42, 0x28, 0xd4, 0x9a, 0x96, 0x08, 0x25, 0xbb, 0x85, 0x1b, 0xd9, 0xb7, 0x6e, 0x81, 0x7c, 0x6f,
	0x3f, 0xd9, 0x0b, 0x28, 0x3a, 0xa9, 0x71, 0xd0, 0x18, 0xac, 0xa4, 0x0e, 0xce, 0x49, 0x25, 0x27,
	0xaf, 0x80, 0x85, 0xb6, 0x56, 0x5e, 0x70, 0xf0, 0x2f, 0x67, 0xae, 0xf5, 0x96, 0xc8, 0x47, 0x0b,
	0x9c, 0x81, 0x15, 0x3c, 0x0a, 0xdd, 0xf8, 0x65, 0x92, 0xea, 0xab, 0x6f, 0xcf, 0x5d, 0xfb, 0x43,
	0x42, 0x1b, 0x47, 0x6c, 0x7f, 0xb5, 0x81, 0xfb, 0x94, 0xe0, 0x07, 0xae, 0xf0, 0x7f, 0xf1, 0x3d,
	0x81, 0xf4, 0xc8, 0x15, 0x5a, 0xe6, 0x63, 0x4b, 0x6c, 0xb9, 0x15, 0xd5, 0xf7, 0xe8, 0xfa, 0x27,
	0x3e, 0xe1, 0x49, 0x36, 0x1d, 0xfe, 0x75, 0x33, 0xbf, 0x8f, 0x8e, 0xff, 0x1c, 0x7d, 0x07, 0xb3,
	0x7e, 0x14, 0xd8, 0x51, 0xde, 0xbe, 0xb0, 0x19, 0x5d, 0xfc, 0xbc, 0x90, 0x91, 0x8f, 0x7c, 0x4e,
	0x2a, 0x65, 0x64, 0x67, 0xbb, 0x63, 0x11, 0xbf, 0xce, 0x87, 0xee, 0x49, 0xfc, 0xfb, 0x7e, 0xde,
	0x3d, 0xfd, 0x5c, 0x86, 0x73, 0x7f, 0x1d, 0xbc, 0x69, 0x54, 0x17, 0xd9, 0xe0, 0x21, 0x71, 0xf2,
	0x9b, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xee, 0x7e, 0x7b, 0x20, 0x03, 0x00, 0x00,
}
