// Code generated by protoc-gen-go. DO NOT EDIT.
// source: distributor_service.proto

package courier_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDistributorResponse struct {
	Distributor          *Distributor `protobuf:"bytes,1,opt,name=distributor,proto3" json:"distributor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateDistributorResponse) Reset()         { *m = CreateDistributorResponse{} }
func (m *CreateDistributorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDistributorResponse) ProtoMessage()    {}
func (*CreateDistributorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d388a02fc33da3, []int{0}
}

func (m *CreateDistributorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDistributorResponse.Unmarshal(m, b)
}
func (m *CreateDistributorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDistributorResponse.Marshal(b, m, deterministic)
}
func (m *CreateDistributorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDistributorResponse.Merge(m, src)
}
func (m *CreateDistributorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDistributorResponse.Size(m)
}
func (m *CreateDistributorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDistributorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDistributorResponse proto.InternalMessageInfo

func (m *CreateDistributorResponse) GetDistributor() *Distributor {
	if m != nil {
		return m.Distributor
	}
	return nil
}

type UpdateDistributorResponse struct {
	Distributor          *Distributor `protobuf:"bytes,1,opt,name=distributor,proto3" json:"distributor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateDistributorResponse) Reset()         { *m = UpdateDistributorResponse{} }
func (m *UpdateDistributorResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDistributorResponse) ProtoMessage()    {}
func (*UpdateDistributorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d388a02fc33da3, []int{1}
}

func (m *UpdateDistributorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDistributorResponse.Unmarshal(m, b)
}
func (m *UpdateDistributorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDistributorResponse.Marshal(b, m, deterministic)
}
func (m *UpdateDistributorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDistributorResponse.Merge(m, src)
}
func (m *UpdateDistributorResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDistributorResponse.Size(m)
}
func (m *UpdateDistributorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDistributorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDistributorResponse proto.InternalMessageInfo

func (m *UpdateDistributorResponse) GetDistributor() *Distributor {
	if m != nil {
		return m.Distributor
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateDistributorResponse)(nil), "genproto.CreateDistributorResponse")
	proto.RegisterType((*UpdateDistributorResponse)(nil), "genproto.UpdateDistributorResponse")
}

func init() { proto.RegisterFile("distributor_service.proto", fileDescriptor_f3d388a02fc33da3) }

var fileDescriptor_f3d388a02fc33da3 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0xc9, 0x2c, 0x2e,
	0x29, 0xca, 0x4c, 0x2a, 0x2d, 0xc9, 0x2f, 0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x4f, 0xcd, 0x03, 0xb3, 0xa4, 0x04, 0x91, 0x14,
	0x41, 0x24, 0x95, 0x42, 0xb8, 0x24, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x5d, 0x10, 0x52, 0x41,
	0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xe6, 0x5c, 0xdc, 0x48, 0x3a, 0x24, 0x18, 0x15,
	0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf5, 0x60, 0xe6, 0xe9, 0x21, 0xeb, 0x41, 0x56, 0x09, 0x32, 0x35,
	0xb4, 0x20, 0x85, 0xca, 0xa6, 0x1a, 0x2d, 0x61, 0xe4, 0x12, 0x42, 0x92, 0x0c, 0x86, 0xf8, 0x52,
	0xc8, 0x8d, 0x8b, 0x0d, 0xe2, 0x05, 0x21, 0xec, 0x86, 0x48, 0x29, 0x23, 0x84, 0x71, 0xfa, 0x55,
	0x89, 0x01, 0x64, 0x0e, 0xc4, 0xd1, 0x44, 0x98, 0x83, 0xd3, 0x77, 0x4a, 0x0c, 0x4e, 0x52, 0x51,
	0x12, 0x30, 0x75, 0xfa, 0xc9, 0xf9, 0xa5, 0x45, 0x99, 0xa9, 0xf0, 0x18, 0x49, 0x62, 0x03, 0x0b,
	0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x57, 0xe9, 0x78, 0xaf, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DistributorServiceClient is the client API for DistributorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DistributorServiceClient interface {
	Create(ctx context.Context, in *Distributor, opts ...grpc.CallOption) (*CreateDistributorResponse, error)
	Update(ctx context.Context, in *Distributor, opts ...grpc.CallOption) (*UpdateDistributorResponse, error)
}

type distributorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDistributorServiceClient(cc grpc.ClientConnInterface) DistributorServiceClient {
	return &distributorServiceClient{cc}
}

func (c *distributorServiceClient) Create(ctx context.Context, in *Distributor, opts ...grpc.CallOption) (*CreateDistributorResponse, error) {
	out := new(CreateDistributorResponse)
	err := c.cc.Invoke(ctx, "/genproto.DistributorService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributorServiceClient) Update(ctx context.Context, in *Distributor, opts ...grpc.CallOption) (*UpdateDistributorResponse, error) {
	out := new(UpdateDistributorResponse)
	err := c.cc.Invoke(ctx, "/genproto.DistributorService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributorServiceServer is the server API for DistributorService service.
type DistributorServiceServer interface {
	Create(context.Context, *Distributor) (*CreateDistributorResponse, error)
	Update(context.Context, *Distributor) (*UpdateDistributorResponse, error)
}

// UnimplementedDistributorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDistributorServiceServer struct {
}

func (*UnimplementedDistributorServiceServer) Create(ctx context.Context, req *Distributor) (*CreateDistributorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedDistributorServiceServer) Update(ctx context.Context, req *Distributor) (*UpdateDistributorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterDistributorServiceServer(s *grpc.Server, srv DistributorServiceServer) {
	s.RegisterService(&_DistributorService_serviceDesc, srv)
}

func _DistributorService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Distributor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributorServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistributorService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributorServiceServer).Create(ctx, req.(*Distributor))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributorService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Distributor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributorServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistributorService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributorServiceServer).Update(ctx, req.(*Distributor))
	}
	return interceptor(ctx, in, info, handler)
}

var _DistributorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.DistributorService",
	HandlerType: (*DistributorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DistributorService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DistributorService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "distributor_service.proto",
}
